### ISSUE TITLE
throwHttpErrorResponse function returns an unclosed observable

### ISSUE THREAD

**Issue by Takumi-kun** [peopleware/angular-sdk#7]
The function [`throwHttpErrorResponse()`](https://github.com/peopleware/angular-sdk/blob/0ef226219a9d176619be00d02193d5f506916596/projects/ppwcode/ng-unit-testing/src/lib/http/throw-error-response.ts#L4) returns an observable that is not completed. This causes an issue in unit tests where the result is only returned after the observable(s) are finalized, for example when using `forkJoin` in a facade method. In that case the `forkJoin` waits until all observables are completed, which results in a timeout in the unit test.

The first thought to solve this issue was to pipe on the error observable and return the first result (as shown below), but that doesn't work as expected. This still doesn't finalize the observable, possibly because of the error status.

```
export const throwHttpErrorResponse = (statusCode: number): Observable<never> =>
    throwError(
        () =>
            new HttpErrorResponse({
                error: `Error ${statusCode}`,
                status: statusCode
            })
    ).pipe(first())
```

**Comment by maaso** [comment]
See also https://www.learnrxjs.io/learn-rxjs/operators/combination/forkjoin, Example #5

**Comment by glenstaes** [comment]
@maaso The issue there is that the subscriber will have its "next" callback executed instead of the "error" callback we intend to get executed.

**Comment by glenstaes** [comment]
@Takumi-kun 

After some investigation, I noticed that this has nothing to do with the `throwHttpErrorResponse`, but more with the way the `expectHttpError` handles errors that have risen. Since we are always using the `expectAsyncResultHttpError` and `expectPagedAsyncResultHttpError` functions in our facades, the `expectHttpError` is used with `complete = false` as third parameter because it is not explicitly set.

This means that the stream will not complete after passing the `expectAsyncResultHttpError` or `expectPagedAsyncResultHttpError`. This is clearly visible when using the `finalize` operator on the full stream pipeline:
```typescript
return this.service.get().pipe(
    map((r) => createSuccessAsyncResult(r)),
    finalize(() => console.log('finalize 1')), // This will get logged.
    expectAsyncResultHttpError([404], null),
    finalize(() => console.log('finalize 2')), // But this won't.
)
```

I have introduced a third parameter to both functions: `completeOnError` which defaults to `true`. The parameter is passed to the `expectHttpError`. This looks like a breaking change because the default of the flag for `expectHttpError` is `false`. However, I'm confident that this will not actually break anything since these functions are used in the pipeline of an `Observable` returned by the service and thus by an HTTP call. HTTP calls will only emit once so there's no reason to keep the stream open. That's possibly also the reason why `'finalize 1'` gets logged anyway.

The fix will be available in the next version.
